name: nakama-research
data_dir: "./data/"

logger:
  level: "info"
  stdout: true
  file: ""

runtime:
  env:
    - "DEBUG=1"
  go:
    modules_path: "/nakama/data/modules"

match:
  input_queue_size: 128
  call_queue_size: 128
  join_attempt_queue_size: 128
  max_players: 8

matchmaker:
  max_tickets: 1000
  interval_sec: 5
  max_intervals: 20
  min_party_size: 2
  max_party_size: 8
  # Use level-based matchmaking
  level_range: 5

console:
  port: 7351
  username: "admin"
  password: "password"
  signing_key: "defaultkey"
  token_expiry_sec: 86400
  max_message_size_bytes: 4096

socket:
  server_key: "defaultkey"
  port: 7350
  max_message_size_bytes: 4096
  max_request_size_bytes: 32768
  read_buffer_size_bytes: 4096
  write_buffer_size_bytes: 4096
  ping_period_ms: 15000
  pong_wait_ms: 25000
  write_wait_ms: 10000

session:
  encryption_key: "defaultencryptionkey"
  token_expiry_sec: 86400
  refresh_encryption_key: "defaultrefreshencryptionkey"
  refresh_token_expiry_sec: 2592000

social:
  steam:
    publisher_key: ""
    app_id: 0

tracker:
  event_queue_size: 65536
